@extends('layouts.admin')

@section('title', __('Dashboard Superadmin'))
@section('page-title', __('Dashboard Superadmin'))
@section('page-subtitle', __('Pantau pertumbuhan aplikasi, aktivitas booking, dan operasional provider.'))

@section('content')
    <div class="admin-dashboard-hero"><div><span class="admin-dashboard-eyebrow">{{ __('CONTROL CENTER') }}</span><h2>{{ __('Selamat datang kembali, :name.', ['name' => auth()->user()->name]) }}</h2><p>{{ __('Semua informasi penting aplikasi dalam satu tampilan ringkas.') }}</p></div><div class="admin-dashboard-hero-icon"><i class="fas fa-chart-line"></i></div></div>
    <div class="content-card admin-plan-distribution-card mb-4"><div class="card-heading"><div><h5>{{ __('Distribusi provider berdasarkan paket') }}</h5><p>{{ __('Lihat jumlah pengguna provider pada setiap paket yang tersedia.') }}</p></div><span class="admin-plan-total"><i class="fas fa-users me-1"></i>{{ number_format($providerTotal, 0, ',', '.') }} {{ __('provider') }}</span></div><div class="row g-3">@forelse($planDistribution as $plan)<div class="col-12 col-md-6 col-xl-4"><div class="admin-plan-item"><div class="d-flex justify-content-between align-items-center gap-2"><span class="admin-plan-name"><i class="fas fa-gem me-2"></i>{{ $plan['name'] }}</span><strong>{{ number_format($plan['count'], 0, ',', '.') }}</strong></div><div class="admin-plan-track"><span style="width: {{ max($plan['percentage'], $plan['count'] > 0 ? 3 : 0) }}%"></span></div><small>{{ $plan['percentage'] }}% {{ __('dari provider') }} @unless($plan['is_active']) · {{ __('nonaktif') }} @endunless</small></div></div>@empty<div class="col-12"><div class="report-empty-state"><i class="fas fa-box-open"></i><p>{{ __('Belum ada paket provider.') }}</p></div></div>@endforelse<div class="col-12 col-md-6 col-xl-4"><div class="admin-plan-item is-unassigned"><div class="d-flex justify-content-between align-items-center gap-2"><span class="admin-plan-name"><i class="fas fa-user-clock me-2"></i>{{ __('Tanpa paket') }}</span><strong>{{ number_format($unassignedProviders, 0, ',', '.') }}</strong></div><div class="admin-plan-track"><span style="width: {{ $providerTotal > 0 ? max(round(($unassignedProviders / $providerTotal) * 100), $unassignedProviders > 0 ? 3 : 0) : 0 }}%"></span></div><small>{{ $providerTotal > 0 ? round(($unassignedProviders / $providerTotal) * 100) : 0 }}% {{ __('dari provider') }}</small></div></div></div></div>

    <div class="row g-4 mt-1 mb-4">@foreach ($stats as $stat)<div class="col-12 col-sm-6 col-xl-3"><div class="stat-card admin-stat-card"><div class="d-flex justify-content-between align-items-start"><div><p class="stat-label">{{ __($stat['label']) }}</p><h2>{{ number_format($stat['value'], 0, ',', '.') }}</h2></div><div class="stat-icon icon-{{ $stat['color'] }}"><i class="{{ $stat['icon'] }}"></i></div></div><div class="stat-foot"><span class="text-muted">{{ __($stat['note']) }}</span></div></div></div>@endforeach</div>

    <div class="row g-4 mb-4"><div class="col-12 col-xl-8"><div class="content-card admin-chart-card h-100"><div class="card-heading"><div><h5>{{ __('Tren aktivitas aplikasi') }}</h5><p>{{ __('Perbandingan booking dan upgrade paket dalam 6 bulan terakhir.') }}</p></div><span class="admin-chart-legend"><i class="legend-booking"></i>{{ __('Booking') }} <i class="legend-upgrade"></i>{{ __('Upgrade disetujui') }}</span></div><div class="admin-chart-wrap"><canvas id="activityTrendChart"></canvas></div></div></div><div class="col-12 col-xl-4"><div class="content-card admin-chart-card h-100"><div class="card-heading"><div><h5>{{ __('Status booking') }}</h5><p>{{ __('Distribusi seluruh booking.') }}</p></div></div><div class="admin-doughnut-wrap"><canvas id="bookingStatusChart"></canvas></div><div class="admin-status-list">@foreach ($bookingStatuses as $status => $total)<div><span><i class="status-dot status-dot-{{ $status }}"></i>{{ __(ucfirst($status)) }}</span><strong>{{ number_format($total, 0, ',', '.') }}</strong></div>@endforeach</div></div></div></div>

    <div class="row g-4 mb-4"><div class="col-12 col-lg-4"><div class="content-card admin-summary-card"><div class="admin-summary-icon icon-warning"><i class="fas fa-hourglass-half"></i></div><div><small>{{ __('Pengajuan provider menunggu') }}</small><strong>{{ $pendingApplications }}</strong><a href="{{ route('admin.provider-applications.index') }}">{{ __('Tinjau pengajuan') }} <i class="fas fa-arrow-right ms-1"></i></a></div></div></div><div class="col-12 col-lg-4"><div class="content-card admin-summary-card"><div class="admin-summary-icon icon-primary"><i class="fas fa-file-invoice-dollar"></i></div><div><small>{{ __('Upgrade paket menunggu') }}</small><strong>{{ $pendingUpgrades }}</strong><a href="{{ route('admin.provider-plan-upgrades.index') }}">{{ __('Validasi upgrade') }} <i class="fas fa-arrow-right ms-1"></i></a></div></div></div><div class="col-12 col-lg-4"><div class="content-card admin-summary-card"><div class="admin-summary-icon icon-success"><i class="fas fa-wallet"></i></div><div><small>{{ __('Pendapatan terdata bulan ini') }}</small><strong>Rp {{ number_format((float) ($confirmedRevenue + $approvedUpgradeRevenue), 0, ',', '.') }}</strong><span>{{ __('Booking + upgrade paket') }}</span></div></div></div></div>

    <div class="content-card"><div class="card-heading"><div><h5>{{ __('Pengajuan upgrade terbaru') }}</h5><p>{{ __('Pantau pengajuan paket yang perlu ditinjau.') }}</p></div><a href="{{ route('admin.provider-plan-upgrades.index') }}" class="small text-primary text-decoration-none">{{ __('Lihat semua') }} <i class="fas fa-arrow-right ms-1"></i></a></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>{{ __('Provider') }}</th><th>{{ __('Paket') }}</th><th>{{ __('Jenis') }}</th><th>{{ __('Nominal') }}</th><th>{{ __('Status') }}</th></tr></thead><tbody>@forelse($recentUpgrades as $upgrade)<tr><td><strong>{{ $upgrade->provider->name }}</strong><small class="d-block text-muted">{{ $upgrade->created_at->format('d M Y H:i') }}</small></td><td>{{ $upgrade->providerPlan->name }}</td><td>@if($upgrade->is_prorated)<span class="status status-info">{{ __('Prorata') }}</span>@else<span class="status status-primary">{{ __('Dari awal') }}</span>@endif</td><td>Rp {{ number_format((float) $upgrade->amount, 0, ',', '.') }}</td><td><span class="status {{ $upgrade->status === 'approved' ? 'status-success' : ($upgrade->status === 'rejected' ? 'status-danger' : 'status-warning') }}">{{ ucfirst($upgrade->status) }}</span></td></tr>@empty<tr><td colspan="5" class="text-center text-muted py-4">{{ __('Belum ada pengajuan upgrade.') }}</td></tr>@endforelse</tbody></table></div></div>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.4/dist/chart.umd.min.js"></script>
<script>
    (() => {
        if (typeof Chart === 'undefined') return;
        const styles = getComputedStyle(document.documentElement);
        const muted = styles.getPropertyValue('--muted').trim() || '#8690aa';
        const line = styles.getPropertyValue('--line').trim() || '#edf0f7';
        const purple = styles.getPropertyValue('--purple').trim() || '#6c63ff';
        const green = '#16b979';
        new Chart(document.getElementById('activityTrendChart'), {type: 'line', data: {labels: @json($monthLabels), datasets: [{label: @json(__('Booking')), data: @json($bookingTrend), borderColor: purple, backgroundColor: 'rgba(108,99,255,.12)', fill: true, tension: .35, pointRadius: 3}, {label: @json(__('Upgrade disetujui')), data: @json($upgradeTrend), borderColor: green, backgroundColor: 'transparent', tension: .35, pointRadius: 3}]}, options: {responsive: true, maintainAspectRatio: false, interaction: {mode: 'index', intersect: false}, plugins: {legend: {display: false}}, scales: {x: {grid: {display: false}, ticks: {color: muted, font: {size: 10}}}, y: {beginAtZero: true, grid: {color: line}, ticks: {color: muted, precision: 0, font: {size: 10}}}}}});
        const statusLabels = @json($bookingStatuses->keys()->map(fn ($status) => __(ucfirst($status))));
        const statusValues = @json($bookingStatuses->values());
        new Chart(document.getElementById('bookingStatusChart'), {type: 'doughnut', data: {labels: statusLabels, datasets: [{data: statusValues, backgroundColor: ['#6c63ff', '#16b979', '#e9a514', '#f05b72', '#9aa3b8'], borderWidth: 0}]}, options: {responsive: true, maintainAspectRatio: false, cutout: '70%', plugins: {legend: {display: false}}}});
    })();
</script>
@endsection
