@extends('layouts.admin')

@section('title', 'Dashboard Pengguna')
@section('page-title', 'Dashboard Pengguna')
@section('page-subtitle', 'Ringkasan akun, booking, dan pengajuan provider Anda.')

@section('content')
    <div class="provider-dashboard-hero user-dashboard-hero"><div><p class="eyebrow">RUANG PENGGUNA</p><h2>Selamat datang, {{ auth()->user()->name }}.</h2><p>Kelola aktivitas booking dan pantau proses pengajuan provider Anda.</p></div><div class="d-flex flex-wrap gap-2"><a href="{{ route('places.index') }}" class="btn btn-light"><i class="fas fa-compass me-2"></i>Jelajahi tempat</a><a href="{{ route('profile') }}" class="btn btn-outline-light"><i class="fas fa-user me-2"></i>Profil saya</a></div></div>

    <div class="row g-4 mt-1">
        <div class="col-12 col-md-4"><div class="stat-card user-stat-card"><p class="stat-label">Booking mendatang</p><h2>{{ $upcomingBookingCount }}</h2><div class="stat-foot"><a href="{{ route('bookings.index', ['display' => 'list']) }}" class="text-primary text-decoration-none">Lihat booking saya <i class="fas fa-arrow-right ms-1"></i></a></div></div></div>
        <div class="col-12 col-md-4"><div class="stat-card user-stat-card"><p class="stat-label">Total booking</p><h2>{{ $bookingCount }}</h2><div class="stat-foot"><span class="text-muted">Termasuk riwayat booking</span></div></div></div>
        <div class="col-12 col-md-4"><div class="stat-card user-stat-card"><p class="stat-label">Kelengkapan profil</p><h2>{{ $profileCompletion }}%</h2><div class="stat-foot"><a href="{{ route('profile') }}" class="text-primary text-decoration-none">Lengkapi profil <i class="fas fa-arrow-right ms-1"></i></a></div></div></div>
    </div>

    <div class="row g-4 mt-1">
        <div class="col-12 col-xl-7">
            <div class="content-card h-100 user-information-card"><div class="card-heading mb-4"><div><h5 class="mb-1">Informasi akun</h5><p class="mb-0">Data utama yang digunakan dalam aktivitas Anda.</p></div><span class="user-info-avatar">{{ strtoupper(substr(auth()->user()->name, 0, 1)) }}</span></div><div class="user-information-grid"><div><small>Nama pengguna</small><strong>{{ auth()->user()->name }}</strong></div><div><small>Email</small><strong>{{ auth()->user()->email }}</strong></div><div><small>Nomor telepon</small><strong>{{ auth()->user()->phone ?: 'Belum diisi' }}</strong></div><div><small>Lokasi</small><strong>{{ auth()->user()->location ?: 'Belum diisi' }}</strong></div></div><a href="{{ route('profile') }}" class="btn btn-light btn-sm mt-4"><i class="fas fa-pen me-2"></i>Perbarui informasi</a></div>
        </div>
        <div class="col-12 col-xl-5">
            <div class="content-card h-100 provider-application-summary"><div class="card-heading mb-3"><div><h5 class="mb-1">Pengajuan provider</h5><p class="mb-0">Dapatkan akses untuk mengelola bisnis Anda.</p></div><i class="fas fa-store-alt application-summary-icon"></i></div>@if (!$latestApplication)<div class="application-status-panel is-ready"><span><i class="fas fa-paper-plane"></i></span><div><strong>Belum ada pengajuan</strong><small>Ajukan bisnis Anda untuk ditinjau superadmin.</small></div></div><a href="{{ route('provider-application.create') }}" class="btn btn-primary w-100 mt-4"><i class="fas fa-paper-plane me-2"></i>Ajukan sebagai provider</a>@elseif($latestApplication->status === 'pending')<div class="application-status-panel is-pending"><span><i class="fas fa-hourglass-half"></i></span><div><strong>Sedang ditinjau</strong><small>Pengajuan {{ $latestApplication->business_name }} menunggu validasi superadmin.</small></div></div><a href="{{ route('provider-application.create') }}" class="btn btn-light w-100 mt-4">Lihat detail pengajuan</a>@elseif($latestApplication->status === 'approved')<div class="application-status-panel is-approved"><span><i class="fas fa-circle-check"></i></span><div><strong>Pengajuan disetujui</strong><small>Akun Anda sudah memiliki akses provider.</small></div></div>@else<div class="application-status-panel is-rejected"><span><i class="fas fa-circle-xmark"></i></span><div><strong>Pengajuan perlu diperbaiki</strong><small>{{ $latestApplication->rejection_reason ?: 'Silakan periksa kembali data bisnis Anda.' }}</small></div></div><a href="{{ route('provider-application.create') }}" class="btn btn-primary w-100 mt-4">Ajukan kembali</a>@endif</div>
        </div>
    </div>

    <div class="content-card mt-4 provider-role-card"><div class="d-flex flex-column flex-lg-row align-items-lg-center justify-content-between gap-4"><div><p class="eyebrow mb-2">{{ __('UNTUK PEMILIK BISNIS') }}</p><h4 class="mb-2">{{ __('Kelola tempat Anda sebagai Provider') }}</h4><p class="text-muted mb-0">{{ __('Provider adalah pengguna yang telah mendapat akses untuk mendaftarkan dan mengelola tempat bisnis, layanan, serta jadwalnya di aplikasi.') }}</p></div><a href="{{ route('provider-application.create') }}" class="btn btn-primary text-nowrap"><i class="fas fa-arrow-right me-2"></i>Lihat halaman pengajuan</a></div><div class="row g-3 mt-2"><div class="col-md-4"><div class="provider-benefit"><span><i class="fas fa-store"></i></span><div><strong>{{ __('Tampilkan bisnis Anda') }}</strong><small>{{ __('Tempat lebih mudah ditemukan oleh calon pelanggan.') }}</small></div></div></div><div class="col-md-4"><div class="provider-benefit"><span><i class="fas fa-calendar-check"></i></span><div><strong>{{ __('Atur layanan dan jadwal') }}</strong><small>{{ __('Kelola informasi layanan dan jam operasional dalam satu dashboard.') }}</small></div></div></div><div class="col-md-4"><div class="provider-benefit"><span><i class="fas fa-users"></i></span><div><strong>{{ __('Jangkau lebih banyak pelanggan') }}</strong><small>{{ __('Bantu pelanggan menemukan dan memesan tempat Anda.') }}</small></div></div></div></div></div>

    <div class="content-card mt-4"><div class="card-heading"><div><h5>{{ __('Temukan tempat dan booking') }}</h5><p>{{ __('Lihat tempat, layanan, dan jadwal yang tersedia untuk Anda.') }}</p></div><a href="{{ route('places.index') }}" class="btn btn-primary btn-sm">{{ __('Jelajahi tempat') }}</a></div><div class="provider-empty-state"><i class="fas fa-compass"></i><p>{{ __('Mulai jelajahi tempat untuk membuat booking pertama Anda.') }}</p><a href="{{ route('bookings.index') }}" class="text-primary text-decoration-none">{{ __('Lihat booking saya') }}</a></div></div>
@endsection
