@extends('layouts.admin')

@section('title', $pageTitle)
@section('page-title', $pageTitle)
@section('page-subtitle', 'Tentukan kapasitas dan harga layanan provider.')

@section('content')
    <div class="content-card provider-plan-form-shell">
        @if ($errors->any())<div class="alert alert-danger small">{{ $errors->first() }}</div>@endif
        <form method="POST" action="{{ $providerPlan->exists ? route('admin.provider-plans.update', $providerPlan) : route('admin.provider-plans.store') }}">
            @csrf @if ($providerPlan->exists) @method('PUT') @endif
            <div class="provider-plan-form-intro"><span class="provider-plan-form-icon"><i class="fas fa-box-open"></i></span><div><h4>{{ $providerPlan->exists ? 'Perbarui paket provider' : 'Buat paket provider' }}</h4><p>{{ __('Semua batas akan diterapkan otomatis pada provider yang menggunakan paket ini.') }}</p></div></div>
            <div class="row g-3"><div class="col-md-7"><label class="form-label" for="name">{{ __('Nama paket') }}</label><input id="name" name="name" class="form-control" value="{{ old('name', $providerPlan->name) }}" placeholder="Contoh: Professional" required></div><div class="col-md-5"><label class="form-label" for="monthly_price">{{ __('Harga per bulan') }}</label><div class="input-group"><span class="input-group-text">Rp</span><input id="monthly_price" type="number" name="monthly_price" class="form-control" value="{{ old('monthly_price', $providerPlan->monthly_price) }}" min="0" step="0.01" required></div></div><div class="col-12"><label class="form-label" for="description">{{ __('Deskripsi') }}</label><textarea id="description" name="description" class="form-control" rows="3" placeholder="Jelaskan target pengguna paket ini">{{ old('description', $providerPlan->description) }}</textarea></div><div class="col-12"><label class="form-label" for="payment_instruction">{{ __('Instruksi pembayaran') }} <span class="text-muted">(opsional)</span></label><textarea id="payment_instruction" name="payment_instruction" class="form-control" rows="3" placeholder="Contoh: Transfer ke BCA 123456789 a.n. Nama Perusahaan atau scan QRIS berikut...">{{ old('payment_instruction', $providerPlan->payment_instruction) }}</textarea><small class="text-muted">{{ __('Instruksi ini akan ditampilkan kepada provider saat mengajukan upgrade.') }}</small></div></div>
            <div class="provider-plan-limit-editor mt-4"><div class="section-title"><span class="section-number"><i class="fas fa-sliders"></i></span><div><h5>{{ __('Batas penggunaan') }}</h5><p>{{ __('Penyediaan kapasitas sesuai kebutuhan paket.') }}</p></div></div><div class="row g-3"><div class="col-md-4"><label class="form-label" for="max_business_places">{{ __('Maksimal bisnis') }}</label><input id="max_business_places" type="number" name="max_business_places" class="form-control" value="{{ old('max_business_places', $providerPlan->max_business_places ?: 1) }}" min="1" required><small class="text-muted">{{ __('Jumlah tempat bisnis aktif yang dapat dikelola.') }}</small></div><div class="col-md-4"><label class="form-label" for="max_services_per_place">{{ __('Layanan per bisnis') }}</label><input id="max_services_per_place" type="number" name="max_services_per_place" class="form-control" value="{{ old('max_services_per_place', $providerPlan->max_services_per_place ?: 1) }}" min="1" required><small class="text-muted">{{ __('Batas layanan pada setiap tempat bisnis.') }}</small></div><div class="col-md-4"><label class="form-label" for="max_bookings_per_month">{{ __('Booking per bulan') }}</label><input id="max_bookings_per_month" type="number" name="max_bookings_per_month" class="form-control" value="{{ old('max_bookings_per_month', $providerPlan->max_bookings_per_month ?: 1) }}" min="1" required><small class="text-muted">{{ __('Booking diterima dari seluruh bisnis provider.') }}</small></div></div></div>
            <div class="form-check form-switch mt-4"><input id="is_active" type="checkbox" name="is_active" value="1" class="form-check-input" @checked(old('is_active', $providerPlan->exists ? $providerPlan->is_active : true))><label for="is_active" class="form-check-label">{{ __('Paket aktif dan dapat diberikan ke provider') }}</label></div>
            <div class="d-flex justify-content-end gap-2 mt-4"><a href="{{ route('admin.provider-plans.index') }}" class="btn btn-light">{{ __('Batal') }}</a><button class="btn btn-primary"><i class="fas fa-check me-1"></i>{{ __('Simpan paket') }}</button></div>
        </form>
    </div>
@endsection
