@extends('layouts.admin')

@php($editing = $businessService->exists)
@php($isActive = (string) old('is_active', $businessService->exists ? (int) $businessService->is_active : 1) === '1')
@section('title', $editing ? 'Edit Layanan' : 'Tambah Layanan')
@section('page-title', $editing ? 'Edit Layanan' : 'Tambah Layanan')
@section('page-subtitle', $businessPlace->name)

@section('content')
    <div class="business-service-editor">
        <div class="business-service-hero"><div><p class="eyebrow">{{ $editing ? 'PERBARUI LAYANAN' : 'TAMBAHKAN LAYANAN BARU' }}</p><h2>{{ $editing ? 'Buat layanan Anda semakin menarik.' : 'Hadirkan fasilitas terbaik di tempat Anda.' }}</h2><p>Tambahkan foto dan detail layanan agar pelanggan dapat memilih fasilitas yang paling sesuai.</p></div><div class="business-service-hero-icon"><i class="fas fa-futbol"></i></div></div>
        @if ($errors->any())<div class="alert alert-danger mt-3 mb-0"><i class="fas fa-circle-exclamation me-2"></i>{{ $errors->first() }}</div>@endif
        <div class="business-service-form-grid">
            <div class="business-service-card">
                <div class="business-service-card-heading"><span class="number">01</span><div><h5>Profil layanan</h5><p>Informasi yang akan dilihat pelanggan saat memilih fasilitas.</p></div></div>
                <form method="POST" action="{{ $editing ? route('provider.business-places.services.update', [$businessPlace, $businessService]) : route('provider.business-places.services.store', $businessPlace) }}" enctype="multipart/form-data">
                    @csrf @if ($editing) @method('PUT') @endif
                    <div class="business-service-cover-upload mb-4"><div class="business-service-cover-preview" id="service-cover-preview">@if ($businessService->cover_image_url)<img src="{{ $businessService->cover_image_url }}" alt="{{ $businessService->name }}">@else<i class="fas fa-image"></i><span>Belum ada gambar layanan</span>@endif</div><div class="business-service-cover-copy"><label class="form-label" for="cover_image">Gambar layanan</label><p>Gunakan foto lapangan atau fasilitas yang jelas dan menarik.</p><label class="btn btn-light btn-sm business-service-upload-button" for="cover_image"><i class="fas fa-camera me-1"></i>Pilih gambar</label><input id="cover_image" type="file" name="cover_image" class="d-none" accept="image/jpeg,image/png,image/webp"><div class="business-service-field-hint">JPG, PNG, atau WEBP · Maksimal 5 MB</div></div></div>
                    <div class="business-service-form-grid-fields"><div><label class="form-label" for="name">Nama layanan / lapangan</label><input id="name" name="name" class="form-control form-control-lg" value="{{ old('name', $businessService->name) }}" placeholder="Contoh: Lapangan Tenis 1" required><div class="business-service-field-hint"><i class="fas fa-sparkles me-1"></i>Gunakan nama yang singkat dan mudah dikenali.</div></div><div><label class="form-label" for="business_category_id">Jenis layanan</label><div class="input-group"><span class="input-group-text"><i class="fas fa-tags"></i></span><select id="business_category_id" name="business_category_id" class="form-select"><option value="">Pilih jenis layanan</option>@foreach ($categories as $category)<option value="{{ $category->id }}" @selected((string) old('business_category_id', $businessService->business_category_id) === (string) $category->id)>{{ $category->name }}</option>@foreach ($category->children as $child)<option value="{{ $child->id }}" @selected((string) old('business_category_id', $businessService->business_category_id) === (string) $child->id)>{{ $category->name }} · {{ $child->name }}</option>@endforeach @endforeach</select></div><div class="business-service-field-hint">Jenis layanan diambil dari kategori bisnis yang dikelola admin.</div></div></div>
                    <div class="mt-4"><label class="form-label" for="description">Deskripsi layanan</label><textarea id="description" name="description" class="form-control" rows="5" maxlength="2000" placeholder="Ceritakan ukuran lapangan, fasilitas, atau keunggulan layanan...">{{ old('description', $businessService->description) }}</textarea><div class="business-service-field-hint">Maksimal 2.000 karakter.</div></div>
                    <div class="business-service-status mt-4"><div class="business-service-status-copy"><strong>Status layanan</strong><span>{{ $isActive ? 'Layanan aktif dan dapat diatur jadwalnya.' : 'Layanan nonaktif tidak ditampilkan sebagai pilihan aktif.' }}</span></div><div class="business-service-status-control"><span class="business-service-status-label {{ $isActive ? 'is-active' : '' }}">{{ $isActive ? 'Aktif' : 'Nonaktif' }}</span><label class="business-service-switch" aria-label="Status layanan"><input type="hidden" name="is_active" value="0"><input id="is_active" type="checkbox" name="is_active" value="1" @checked($isActive)><span></span></label></div></div>
                    <div class="business-service-actions"><a href="{{ route('provider.business-places.services.index', $businessPlace) }}" class="btn btn-light">Batal</a><button class="btn btn-primary"><i class="fas fa-check me-2"></i>{{ $editing ? 'Simpan perubahan' : 'Simpan layanan' }}</button></div>
                </form>
            </div>
            <aside class="business-service-card"><div class="business-service-card-heading"><span class="number">02</span><div><h5>Tips layanan menarik</h5><p>Buat informasi fasilitas lebih mudah dipahami.</p></div></div><div class="business-service-tips"><div class="business-service-tip"><i class="fas fa-image"></i><div><strong>Pilih foto yang jelas</strong><p>Tampilkan kondisi lapangan dari sudut terbaik.</p></div></div><div class="business-service-tip"><i class="fas fa-list-check"></i><div><strong>Lengkapi detail</strong><p>Jenis dan deskripsi membantu pelanggan menemukan layanan yang tepat.</p></div></div><div class="business-service-tip"><i class="fas fa-calendar-days"></i><div><strong>Atur jadwal berikutnya</strong><p>Setelah tersimpan, tentukan hari dan jam berulang layanan ini.</p></div></div></div><div class="mt-4 p-3 rounded-3 bg-body-tertiary small text-muted"><i class="fas fa-lightbulb text-warning me-2"></i>Foto layanan yang relevan membuat pilihan pelanggan lebih meyakinkan.</div></aside>
        </div>
    </div>
    <script>document.getElementById('cover_image')?.addEventListener('change', event => { const file = event.target.files?.[0]; if (!file) return; const preview = document.getElementById('service-cover-preview'); const image = document.createElement('img'); image.alt = 'Preview gambar layanan'; image.src = URL.createObjectURL(file); preview.replaceChildren(image); });</script>
@endsection
