@extends('layouts.admin')

@section('title', 'Upgrade Paket Provider')
@section('page-title', 'Upgrade Paket Provider')
@section('page-subtitle', 'Validasi pembayaran dan aktivasi paket provider.')

@section('content')
    @if (session('success'))<div class="alert alert-success small">{{ session('success') }}</div>@endif
    @if ($errors->any())<div class="alert alert-danger small">{{ $errors->first() }}</div>@endif
    <div class="content-card">
        <form method="GET" class="row g-2 mb-4"><div class="col-md-4"><select name="status" class="form-select"><option value="">{{ __('Semua status') }}</option><option value="pending" @selected(request('status') === 'pending')>{{ __('Menunggu') }}</option><option value="approved" @selected(request('status') === 'approved')>{{ __('Disetujui') }}</option><option value="rejected" @selected(request('status') === 'rejected')>{{ __('Ditolak') }}</option></select></div><div class="col-md-3"><button class="btn btn-light">{{ __('Filter') }}</button></div></form>
        <div class="card-heading"><div><h5>{{ __('Pengajuan upgrade') }}</h5><p>{{ $upgrades->count() }} {{ __('pengajuan ditemukan.') }}</p></div></div>
        <div class="table-responsive"><table class="table align-middle"><thead><tr><th>{{ __('PROVIDER') }}</th><th>{{ __('PAKET') }}</th><th>{{ __('JENIS UPGRADE') }}</th><th>{{ __('NOMINAL') }}</th><th>{{ __('BUKTI') }}</th><th>{{ __('STATUS') }}</th><th>{{ __('AKSI') }}</th></tr></thead><tbody>
            @forelse ($upgrades as $upgrade)
                <tr><td><strong>{{ $upgrade->provider->name }}</strong><small class="d-block text-muted">{{ $upgrade->provider->email }}</small></td><td class="fw-semibold">{{ $upgrade->providerPlan->name }}</td><td>@if($upgrade->is_prorated)<span class="status status-info"><i class="fas fa-calculator me-1"></i>{{ __('Prorata') }}</span><small class="d-block text-muted mt-1">{{ $upgrade->proration_remaining_days }} / {{ $upgrade->proration_total_days }} {{ __('hari tersisa') }}</small>@else<span class="status status-primary"><i class="fas fa-play me-1"></i>{{ __('Dari awal') }}</span><small class="d-block text-muted mt-1">{{ __('Periode penuh') }}</small>@endif</td><td>Rp {{ number_format((float) $upgrade->amount, 0, ',', '.') }}<small class="d-block text-muted">{{ $upgrade->payment_method ?: '-' }}</small></td><td>@if($upgrade->payment_proof)<a href="{{ asset('storage/'.$upgrade->payment_proof) }}" target="_blank" rel="noopener" class="btn btn-sm btn-light"><i class="fas fa-file-invoice-dollar me-1"></i>{{ __('Lihat bukti') }}</a>@else<span class="text-muted small">{{ __('Tidak ada bukti') }}</span>@endif</td><td><span class="status {{ $upgrade->status === 'approved' ? 'status-success' : ($upgrade->status === 'rejected' ? 'status-danger' : 'status-warning') }}">{{ ucfirst($upgrade->status) }}</span>@if($upgrade->rejection_reason)<small class="d-block text-danger mt-1">{{ $upgrade->rejection_reason }}</small>@endif</td><td>@if($upgrade->status === 'pending')<div class="d-flex gap-2"><form method="POST" action="{{ route('admin.provider-plan-upgrades.approve', $upgrade) }}">@csrf @method('PATCH')<button class="btn btn-sm btn-success" data-confirm-trigger="{{ __('Setujui upgrade ini?') }}"><i class="fas fa-check"></i></button></form><button class="btn btn-sm btn-outline-danger" type="button" data-bs-toggle="modal" data-bs-target="#rejectUpgrade{{ $upgrade->id }}"><i class="fas fa-xmark"></i></button></div><div class="modal fade" id="rejectUpgrade{{ $upgrade->id }}" tabindex="-1"><div class="modal-dialog"><form method="POST" action="{{ route('admin.provider-plan-upgrades.reject', $upgrade) }}" class="modal-content">@csrf @method('PATCH')<div class="modal-header"><h5 class="modal-title">{{ __('Tolak upgrade') }}</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><label class="form-label">{{ __('Alasan penolakan') }}</label><textarea name="rejection_reason" class="form-control" rows="4" required maxlength="1000"></textarea></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">{{ __('Batal') }}</button><button class="btn btn-danger">{{ __('Tolak pengajuan') }}</button></div></form></div></div>@else<span class="text-muted small">{{ $upgrade->reviewed_at?->format('d M Y H:i') }}</span>@endif</td></tr>
            @empty
                <tr><td colspan="7" class="text-center text-muted py-4">{{ __('Belum ada pengajuan upgrade.') }}</td></tr>
            @endforelse
        </tbody></table></div>
    </div>
@endsection
