@extends('layouts.admin')

@section('title', 'Manajemen Pengguna')
@section('page-title', 'Manajemen Pengguna')
@section('page-subtitle', 'Kelola data, role, paket, dan akses pengguna aplikasi.')

@section('content')
    <div class="admin-users-shell">
        <div class="admin-users-hero"><div><span class="admin-users-eyebrow">{{ __('USER MANAGEMENT') }}</span><h2>{{ __('Kelola pengguna dengan lebih teratur.') }}</h2><p>{{ __('Pantau role, paket provider, dan akses setiap akun dari satu halaman.') }}</p></div><a href="{{ route('admin.users.create') }}" class="btn btn-light"><i class="fas fa-user-plus me-2"></i>{{ __('Tambah pengguna') }}</a></div>
        @if (session('success'))<div class="alert alert-success small">{{ session('success') }}</div>@endif
        @if ($errors->any())<div class="alert alert-danger small">{{ $errors->first() }}</div>@endif

        <div class="row g-3 admin-users-overview"><div class="col-12 col-sm-6 col-xl-3"><div class="admin-users-metric"><span class="admin-users-metric-icon icon-primary"><i class="fas fa-users"></i></span><div><small>{{ __('Ditampilkan') }}</small><strong>{{ number_format($users->count(), 0, ',', '.') }}</strong><em>{{ __('akun') }}</em></div></div></div><div class="col-12 col-sm-6 col-xl-3"><div class="admin-users-metric"><span class="admin-users-metric-icon icon-success"><i class="fas fa-store"></i></span><div><small>{{ __('Provider') }}</small><strong>{{ number_format($users->where('role', 'provider')->count(), 0, ',', '.') }}</strong><em>{{ __('pemilik bisnis') }}</em></div></div></div><div class="col-12 col-sm-6 col-xl-3"><div class="admin-users-metric"><span class="admin-users-metric-icon icon-warning"><i class="fas fa-user-clock"></i></span><div><small>{{ __('Pengguna biasa') }}</small><strong>{{ number_format($users->where('role', 'user')->count(), 0, ',', '.') }}</strong><em>{{ __('akun pelanggan') }}</em></div></div></div><div class="col-12 col-sm-6 col-xl-3"><div class="admin-users-metric"><span class="admin-users-metric-icon icon-danger"><i class="fas fa-shield-halved"></i></span><div><small>{{ __('Admin & manager') }}</small><strong>{{ number_format($users->whereIn('role', ['admin', 'manager'])->count(), 0, ',', '.') }}</strong><em>{{ __('akses pengelola') }}</em></div></div></div></div>

        <div class="content-card admin-users-card"><div class="admin-users-toolbar"><div><h5>{{ __('Daftar pengguna') }}</h5><p>{{ __('Kelola akun dan akses paket provider.') }}</p></div><span class="admin-users-count"><i class="fas fa-database me-1"></i>{{ $users->count() }} {{ __('akun ditemukan') }}</span></div><form method="GET" class="admin-users-filters"><div class="admin-users-search"><i class="fas fa-search"></i><input name="search" value="{{ request('search') }}" placeholder="{{ __('Cari nama atau email...') }}"></div><select name="role" class="form-select"><option value="">{{ __('Semua role') }}</option><option value="admin" @selected(request('role') === 'admin')>Admin</option><option value="manager" @selected(request('role') === 'manager')>Manager</option><option value="provider" @selected(request('role') === 'provider')>Provider</option><option value="user" @selected(request('role') === 'user')>User</option></select><div class="admin-users-filter-actions"><button class="btn btn-light"><i class="fas fa-filter me-1"></i>{{ __('Filter') }}</button><a href="{{ route('admin.users') }}" class="btn btn-link text-muted">{{ __('Reset') }}</a></div></form>
            <div class="table-responsive"><table class="table admin-users-table align-middle" data-data-table><thead><tr><th>{{ __('PENGGUNA') }}</th><th>{{ __('ROLE') }}</th><th>{{ __('PAKET PROVIDER') }}</th><th>{{ __('STATUS PAKET') }}</th><th class="text-end">{{ __('AKSI') }}</th></tr></thead><tbody>@forelse ($users as $user)<tr><td><div class="admin-user-identity"><span class="admin-user-avatar">@if($user->avatar)<img src="{{ asset('storage/'.$user->avatar) }}" alt="{{ $user->name }}">@else{{ strtoupper(substr($user->name, 0, 1)) }}@endif</span><div><strong>{{ $user->name }}</strong><small>{{ $user->email }}</small></div></div></td><td><span class="admin-role-badge role-{{ $user->role }}"><i class="fas {{ $user->role === 'admin' ? 'fa-shield-halved' : ($user->role === 'provider' ? 'fa-store' : ($user->role === 'manager' ? 'fa-briefcase' : 'fa-user')) }}"></i>{{ $user->role === 'provider' ? 'Provider' : ucfirst($user->role) }}</span></td><td>@if($user->role === 'provider' && $user->providerPlan)<div class="admin-plan-cell"><span class="admin-plan-mini-icon"><i class="fas fa-gem"></i></span><div><strong>{{ $user->providerPlan->name }}</strong><small>Rp {{ number_format((float) $user->providerPlan->monthly_price, 0, ',', '.') }}/{{ __('bulan') }}</small></div></div>@elseif($user->role === 'provider')<span class="text-muted small">{{ __('Tanpa paket') }}</span>@else<span class="text-muted">—</span>@endif</td><td>@if($user->role === 'provider' && $user->providerPlan)<span class="status {{ $user->providerPlan->isFree() || $user->provider_plan_expires_at?->isFuture() ? 'status-success' : 'status-danger' }}">{{ $user->providerPlan->isFree() ? __('Free aktif') : ($user->provider_plan_expires_at?->isFuture() ? __('Aktif') : __('Berakhir')) }}</span>@else<span class="text-muted small">{{ __('Tidak berlaku') }}</span>@endif</td><td><div class="admin-user-actions"><a href="{{ route('admin.users.edit', $user) }}" class="btn btn-sm btn-light" title="{{ __('Edit pengguna') }}"><i class="fas fa-pen"></i></a>@if($user->role === 'provider' && $user->providerPlan)<form method="POST" action="{{ route('admin.users.revoke-provider-plan', $user) }}" data-confirm="Cabut paket provider ini? Bisnis provider akan dinonaktifkan.">@csrf @method('PATCH')<button class="btn btn-sm btn-light text-warning" title="{{ __('Cabut paket') }}"><i class="fas fa-user-slash"></i></button></form>@endif<form method="POST" action="{{ route('admin.users.destroy', $user) }}" data-confirm="Hapus pengguna ini? Data yang dihapus tidak dapat dikembalikan.">@csrf @method('DELETE')<button class="btn btn-sm btn-light text-danger" title="{{ __('Hapus pengguna') }}"><i class="fas fa-trash"></i></button></form></div></td></tr>@empty<tr><td colspan="5"><div class="admin-users-empty"><i class="fas fa-users-slash"></i><strong>{{ __('Pengguna tidak ditemukan.') }}</strong><small>{{ __('Coba ubah filter atau kata pencarian Anda.') }}</small></div></td></tr>@endforelse</tbody></table></div>
        </div>
    </div>
@endsection
