@extends('layouts.admin')
@php
    $editing = isset($schedule) && $schedule->exists;
    $selectedDay = (int) old('day_of_week', $schedule->day_of_week ?? 1);
    $isClosed = (bool) old('is_closed', $schedule->is_closed ?? false);
    $isActive = (bool) old('is_active', $schedule->is_active ?? true);
    $dayNames = [1 => __('Senin'), 2 => __('Selasa'), 3 => __('Rabu'), 4 => __('Kamis'), 5 => __('Jumat'), 6 => __('Sabtu'), 7 => __('Minggu')];
    $previewLabels = ['noHours' => __('No operating hours'), 'closed' => __('Closed'), 'active' => __('Active'), 'inactive' => __('Inactive')];
    $previewTime = $isClosed ? $previewLabels['noHours'] : old('start_time', isset($schedule) && $schedule->start_time ? substr($schedule->start_time, 0, 5) : '08:00').' - '.old('end_time', isset($schedule) && $schedule->end_time ? substr($schedule->end_time, 0, 5) : '22:00');
    $previewStatus = $isClosed ? $previewLabels['closed'] : ($isActive ? $previewLabels['active'] : $previewLabels['inactive']);
@endphp
@section('title', $editing ? __('Edit Schedule') : __('Add Schedule'))
@section('page-title', $editing ? __('Edit Schedule') : __('Add Schedule'))
@section('page-subtitle', $businessPlace->name.' · '.$businessService->name)
@section('content')
    <div class="schedule-editor">
        <div class="schedule-editor-hero">
            <div><span class="schedule-editor-kicker"><i class="fas fa-calendar-plus me-2"></i>{{ $editing ? __('EDIT SCHEDULE') : __('NEW SCHEDULE') }}</span><h2>{{ $editing ? __('Fine-tune your operating hours.') : __('Set a schedule your customers can trust.') }}</h2><p>{{ __('Create recurring hours for this service and keep its availability easy to understand.') }}</p></div><div class="schedule-editor-hero-icon"><i class="fas fa-clock"></i></div>
        </div>
        @if ($errors->any())<div class="alert alert-danger mt-3 mb-0"><i class="fas fa-circle-exclamation me-2"></i>{{ $errors->first() }}</div>@endif
        <div class="schedule-editor-layout">
            <div class="content-card schedule-form-card">
                <div class="schedule-section-heading"><span class="schedule-section-number">01</span><div><h5>{{ __('Schedule details') }}</h5><p>{{ __('Choose a recurring day and operating hours.') }}</p></div></div>
                <form method="POST" action="{{ $editing ? route('provider.business-places.services.schedules.update', [$businessPlace, $businessService, $schedule]) : route('provider.business-places.services.schedules.store', [$businessPlace, $businessService]) }}">
                    @csrf @if ($editing) @method('PUT') @endif
                    <div class="schedule-field mb-4"><label class="form-label" for="day_of_week"><i class="fas fa-calendar-day me-2"></i>{{ __('Recurring day') }}</label><select id="day_of_week" name="day_of_week" class="form-select schedule-day-select" required>@foreach ([1 => 'Senin', 2 => 'Selasa', 3 => 'Rabu', 4 => 'Kamis', 5 => 'Jumat', 6 => 'Sabtu', 7 => 'Minggu'] as $day => $label)<option value="{{ $day }}" @selected($selectedDay === $day)>{{ __($label) }}</option>@endforeach</select></div>
                    <div class="schedule-time-heading"><div><label class="form-label mb-1"><i class="fas fa-business-time me-2"></i>{{ __('Operating hours') }}</label><p>{{ __('Set the time range when this service is available.') }}</p></div><span class="schedule-time-zone">{{ config('app.timezone') }}</span></div>
                    <div class="row g-3 mb-4"><div class="col-md-6"><div class="schedule-time-field"><label class="form-label" for="start_time">{{ __('Start time') }}</label><div class="input-group"><span class="input-group-text"><i class="fas fa-play"></i></span><input id="start_time" type="time" name="start_time" class="form-control" value="{{ old('start_time', isset($schedule) && $schedule->start_time ? substr($schedule->start_time, 0, 5) : '08:00') }}"></div></div></div><div class="col-md-6"><div class="schedule-time-field"><label class="form-label" for="end_time">{{ __('End time') }}</label><div class="input-group"><span class="input-group-text"><i class="fas fa-stop"></i></span><input id="end_time" type="time" name="end_time" class="form-control" value="{{ old('end_time', isset($schedule) && $schedule->end_time ? substr($schedule->end_time, 0, 5) : '22:00') }}"></div></div></div></div>
                    <div class="schedule-options"><input type="hidden" name="is_closed" value="0"><label class="schedule-option"><input id="is_closed" type="checkbox" name="is_closed" value="1" @checked($isClosed)><span class="schedule-option-icon"><i class="fas fa-moon"></i></span><span class="schedule-option-copy"><strong>{{ __('Closed on this day') }}</strong><small>{{ __('This day repeats as a holiday without operating hours.') }}</small></span><span class="schedule-toggle"></span></label><input type="hidden" name="is_active" value="0"><label class="schedule-option"><input id="is_active" type="checkbox" name="is_active" value="1" @checked($isActive)><span class="schedule-option-icon schedule-option-icon-active"><i class="fas fa-circle-check"></i></span><span class="schedule-option-copy"><strong>{{ __('Active schedule') }}</strong><small>{{ __('Active schedules can be used for customer bookings.') }}</small></span><span class="schedule-toggle"></span></label></div>
                    <div class="schedule-form-actions"><a href="{{ route('provider.business-places.services.schedules.index', [$businessPlace, $businessService]) }}" class="btn btn-light"><i class="fas fa-arrow-left me-2"></i>{{ __('Back to service') }}</a><button class="btn btn-primary"><i class="fas fa-check me-2"></i>{{ __('Save schedule') }}</button></div>
                </form>
            </div>
            <aside class="content-card schedule-preview-card"><div class="schedule-section-heading"><span class="schedule-section-number schedule-section-number-purple">02</span><div><h5>{{ __('Schedule preview') }}</h5><p>{{ __('See the result at a glance.') }}</p></div></div><div class="schedule-preview"><span class="schedule-preview-label">{{ __('Selected day') }}</span><strong id="schedule-preview-day">{{ $dayNames[$selectedDay] }}</strong><div class="schedule-preview-time" id="schedule-preview-time"><i class="fas fa-clock"></i><span>{{ $previewTime }}</span></div><span class="schedule-preview-status {{ $isClosed ? 'is-closed' : ($isActive ? 'is-active' : 'is-inactive') }}" id="schedule-preview-status"><i class="fas {{ $isClosed ? 'fa-moon' : ($isActive ? 'fa-circle-check' : 'fa-circle-pause') }}"></i><span>{{ $previewStatus }}</span></span></div><div class="schedule-tips"><div class="schedule-tip"><i class="fas fa-lightbulb"></i><p>{{ __('Use a closed day for regular holidays or maintenance.') }}</p></div><div class="schedule-tip"><i class="fas fa-wand-magic-sparkles"></i><p>{{ __('You can update this schedule whenever your operating hours change.') }}</p></div></div></aside>
        </div>
    </div>
    <script>(() => { const day = document.getElementById('day_of_week'); const start = document.getElementById('start_time'); const end = document.getElementById('end_time'); const closed = document.getElementById('is_closed'); const active = document.getElementById('is_active'); const previewDay = document.getElementById('schedule-preview-day'); const previewTime = document.getElementById('schedule-preview-time'); const previewStatus = document.getElementById('schedule-preview-status'); const dayNames = @json($dayNames); const labels = @json($previewLabels); const sync = () => { const isClosed = closed.checked; start.disabled = isClosed; end.disabled = isClosed; start.required = !isClosed; end.required = !isClosed; previewDay.textContent = dayNames[day.value]; previewTime.querySelector('span').textContent = isClosed ? labels.noHours : `${start.value || '--:--'} - ${end.value || '--:--'}`; previewStatus.className = `schedule-preview-status ${isClosed ? 'is-closed' : (active.checked ? 'is-active' : 'is-inactive')}`; previewStatus.querySelector('i').className = `fas ${isClosed ? 'fa-moon' : (active.checked ? 'fa-circle-check' : 'fa-circle-pause')}`; previewStatus.querySelector('span').textContent = isClosed ? labels.closed : (active.checked ? labels.active : labels.inactive); }; [day, start, end, closed, active].forEach(element => element?.addEventListener('change', sync)); [start, end].forEach(element => element?.addEventListener('input', sync)); sync(); })();</script>
@endsection
