@extends('layouts.admin')

@php($editing = $businessPlace->exists)
@php($isActive = (string) old('is_active', $businessPlace->exists ? (int) $businessPlace->is_active : 1) === '1')
@section('title', $editing ? 'Edit Tempat Bisnis' : 'Tambah Tempat Bisnis')
@section('page-title', $editing ? 'Edit Tempat Bisnis' : 'Tambah Tempat Bisnis')
@section('page-subtitle', 'Bangun profil lokasi olahraga yang siap dikelola.')

@section('content')
    <div class="business-place-editor">
        <div class="business-place-hero">
            <div class="business-place-hero-content">
                <p class="eyebrow">{{ $editing ? 'PERBARUI PROFIL LOKASI' : 'MULAI TEMPAT BISNIS BARU' }}</p>
                <h2>{{ $editing ? 'Sempurnakan informasi tempat Anda.' : 'Hadirkan tempat olahraga terbaik Anda.' }}</h2>
                <p>Lengkapi informasi dasar agar pelanggan mudah mengenali dan menemukan fasilitas olahraga Anda.</p>
            </div>
            <div class="business-place-hero-icon"><i class="fas fa-building-circle-check"></i></div>
        </div>

        @if ($errors->any())<div class="alert alert-danger mt-3 mb-0"><i class="fas fa-circle-exclamation me-2"></i>{{ $errors->first() }}</div>@endif

        <div class="business-place-form-grid">
            <div class="business-place-card">
                <div class="business-place-card-heading"><span class="number">01</span><div><h5>Identitas tempat</h5><p>Informasi yang akan membantu pelanggan mengenali lokasi Anda.</p></div></div>
                <form method="POST" action="{{ $editing ? route('provider.business-places.update', $businessPlace) : route('provider.business-places.store') }}" enctype="multipart/form-data">
                    @csrf @if ($editing) @method('PUT') @endif
                    <div class="business-place-cover-upload mb-4"><div class="business-place-cover-preview" id="cover-preview">@if ($businessPlace->cover_image_url)<img src="{{ $businessPlace->cover_image_url }}" alt="{{ $businessPlace->name }}">@else<i class="fas fa-image"></i><span>Belum ada gambar cover</span>@endif</div><div class="business-place-cover-copy"><label class="form-label" for="cover_image">Gambar tempat bisnis</label><p>Gunakan foto fasilitas utama agar tempat Anda lebih menarik.</p><label class="btn btn-light btn-sm business-place-upload-button" for="cover_image"><i class="fas fa-camera me-1"></i>Pilih gambar</label><input id="cover_image" type="file" name="cover_image" class="d-none" accept="image/jpeg,image/png,image/webp"><div class="business-place-field-hint">JPG, PNG, atau WEBP · Maksimal 5 MB</div></div></div>
                    <div class="mb-4"><label class="form-label" for="name">Nama tempat bisnis</label><input id="name" name="name" class="form-control form-control-lg" value="{{ old('name', $businessPlace->name) }}" placeholder="Contoh: Arena Sport Center" required><div class="business-place-field-hint"><i class="fas fa-sparkles me-1"></i>Gunakan nama yang singkat, unik, dan mudah diingat.</div></div>
                    @php($selectedCategoryIds = array_map('strval', (array) old('business_category_ids', $businessPlace->businessCategories->pluck('id')->all())))
                    <div class="mb-4"><label class="form-label" for="business_category_ids">Kategori bisnis</label><div class="business-category-picker" data-category-picker><button type="button" class="business-category-picker-toggle" data-category-toggle aria-expanded="false"><span data-category-label>Pilih kategori bisnis</span><i class="fas fa-chevron-down"></i></button><div class="business-category-picker-menu" data-category-menu>@foreach ($categories as $category)<label class="business-category-option"><input type="checkbox" name="business_category_ids[]" value="{{ $category->id }}" data-category-name="{{ $category->name }} (umum)" @checked(in_array((string) $category->id, $selectedCategoryIds, true))><span>{{ $category->name }} <small>(umum)</small></span></label>@foreach ($category->children as $child)<label class="business-category-option business-category-option-child"><input type="checkbox" name="business_category_ids[]" value="{{ $child->id }}" data-category-name="{{ $category->name }} · {{ $child->name }}" @checked(in_array((string) $child->id, $selectedCategoryIds, true))><span>{{ $category->name }} <b>·</b> {{ $child->name }}</span></label>@endforeach @endforeach</div><div class="business-category-selected" data-category-selected></div></div><div class="business-place-field-hint">Pilih satu atau beberapa kategori. Kategori yang dipilih akan tampil di bawah dropdown.</div></div>
                    <div class="mb-4"><label class="form-label" for="description">Deskripsi singkat</label><textarea id="description" name="description" class="form-control" rows="5" maxlength="2000" placeholder="Ceritakan fasilitas, suasana, atau keunggulan tempat Anda...">{{ old('description', $businessPlace->description) }}</textarea><div class="business-place-field-hint">Maksimal 2.000 karakter.</div></div>
                    <div class="row g-3 mt-1"><div class="col-12"><label class="form-label" for="address">Alamat detail</label><div class="input-group"><span class="input-group-text"><i class="fas fa-location-dot"></i></span><input id="address" name="address" class="form-control" value="{{ old('address', $businessPlace->address) }}" placeholder="Nama jalan, nomor, atau patokan"></div></div><div class="col-12"><label class="form-label" for="google_maps_url">Link lokasi Google Maps</label><div class="input-group"><span class="input-group-text"><i class="fab fa-google"></i></span><input id="google_maps_url" type="url" name="google_maps_url" class="form-control" value="{{ old('google_maps_url', $businessPlace->google_maps_url) }}" placeholder="Klik peta untuk membuat link" inputmode="url"><a class="btn btn-light {{ $businessPlace->google_maps_url ? '' : 'd-none' }}" href="{{ $businessPlace->google_maps_url ?: '#' }}" target="_blank" rel="noopener noreferrer" id="maps-preview-link">Buka Maps</a></div><div class="business-place-field-hint">Klik titik lokasi pada peta untuk mengisi koordinat dan membuat link Google Maps.</div></div><div class="col-12"><div id="business-place-picker-map" class="business-place-picker-map"></div></div><div class="col-md-4"><label class="form-label" for="province_code">Provinsi</label><select id="province_code" name="province_code" class="form-select" data-selected-code="{{ old('province_code', $businessPlace->province_code) }}" required><option value="">Memuat provinsi...</option></select><input type="hidden" name="province_name" id="province_name" value="{{ old('province_name', $businessPlace->province_name) }}"></div><div class="col-md-4"><label class="form-label" for="regency_code">Kabupaten / Kota</label><select id="regency_code" name="regency_code" class="form-select" data-selected-code="{{ old('regency_code', $businessPlace->regency_code) }}" required disabled><option value="">Pilih provinsi terlebih dahulu</option></select><input type="hidden" name="regency_name" id="regency_name" value="{{ old('regency_name', $businessPlace->regency_name) }}"></div><div class="col-md-4"><label class="form-label" for="district_code">Kecamatan</label><select id="district_code" name="district_code" class="form-select" data-selected-code="{{ old('district_code', $businessPlace->district_code) }}" required disabled><option value="">Pilih kabupaten/kota terlebih dahulu</option></select><input type="hidden" name="district_name" id="district_name" value="{{ old('district_name', $businessPlace->district_name) }}"></div><div class="col-md-5"><label class="form-label" for="phone">Nomor telepon</label><div class="input-group"><span class="input-group-text"><i class="fas fa-phone"></i></span><input id="phone" name="phone" class="form-control" value="{{ old('phone', $businessPlace->phone) }}" placeholder="08xxxxxxxxxx"></div></div></div>
                    <div class="row g-3 mt-3"><div class="col-md-6"><label class="form-label" for="latitude">Latitude</label><input id="latitude" name="latitude" type="number" class="form-control" value="{{ old('latitude', $businessPlace->latitude) }}" placeholder="Contoh: -8.6705" step="any" min="-90" max="90"><div class="business-place-field-hint">Terisi dari titik yang dipilih pada peta.</div></div><div class="col-md-6"><label class="form-label" for="longitude">Longitude</label><input id="longitude" name="longitude" type="number" class="form-control" value="{{ old('longitude', $businessPlace->longitude) }}" placeholder="Contoh: 115.2126" step="any" min="-180" max="180"></div></div>
                    <div class="business-place-status mt-4"><div class="business-place-status-copy"><strong>Status tempat bisnis</strong><span>{{ $isActive ? 'Tempat aktif siap menerima pengaturan layanan dan jadwal.' : 'Tempat nonaktif tidak ditampilkan sebagai tempat yang siap dikelola.' }}</span></div><div class="business-place-status-control"><span class="business-place-status-label {{ $isActive ? 'is-active' : '' }}">{{ $isActive ? 'Aktif' : 'Nonaktif' }}</span><label class="business-place-switch" aria-label="Status tempat bisnis"><input type="hidden" name="is_active" value="0"><input id="is_active" type="checkbox" name="is_active" value="1" @checked($isActive)><span></span></label></div></div>
                    <div class="business-place-actions"><a href="{{ route('provider.business-places.index') }}" class="btn btn-light">Batal</a><button class="btn btn-primary"><i class="fas fa-check me-2"></i>{{ $editing ? 'Simpan perubahan' : 'Buat tempat bisnis' }}</button></div>
                </form>
            </div>

            <aside class="business-place-card">
                <div class="business-place-card-heading"><span class="number">02</span><div><h5>Langkah berikutnya</h5><p>Setelah tempat dibuat, Anda dapat langsung melengkapinya.</p></div></div>
                <div class="business-place-tips"><div class="business-place-tip"><i class="fas fa-layer-group"></i><div><strong>Tambahkan layanan</strong><p>Buat lapangan tenis, futsal, bulutangkis, atau fasilitas lainnya.</p></div></div><div class="business-place-tip"><i class="fas fa-calendar-days"></i><div><strong>Atur jadwal berulang</strong><p>Tentukan hari dan jam operasional masing-masing layanan.</p></div></div><div class="business-place-tip"><i class="fas fa-wand-magic-sparkles"></i><div><strong>Siap dikelola</strong><p>Perbarui informasi kapan saja sesuai kondisi tempat Anda.</p></div></div></div>
                <div class="mt-4 p-3 rounded-3 bg-body-tertiary small text-muted"><i class="fas fa-lightbulb text-warning me-2"></i>Informasi yang lengkap membuat tempat Anda terlihat lebih profesional.</div>
            </aside>
        </div>
    </div>
    <script>(() => { const regionBase = @json(route('provider.regions', ['level' => 'provinces'])); const province = document.getElementById('province_code'); const regency = document.getElementById('regency_code'); const district = document.getElementById('district_code'); const endpoint = (level, code = '') => `${regionBase.replace('/provinces', `/${level}`)}${code ? `/${encodeURIComponent(code)}` : ''}`; const setOptions = (select, items, placeholder, selectedCode) => { select.replaceChildren(new Option(placeholder, ''), ...items.map(item => new Option(item.name, item.code))); select.disabled = false; if (selectedCode) select.value = selectedCode; }; const load = async (url, select, placeholder, selectedCode) => { select.disabled = true; select.replaceChildren(new Option('Memuat data...', '')); try { const response = await fetch(url, { headers: { Accept: 'application/json' } }); if (!response.ok) throw new Error('Gagal memuat wilayah'); const result = await response.json(); setOptions(select, result.data ?? [], placeholder, selectedCode); } catch (error) { select.replaceChildren(new Option('Wilayah tidak dapat dimuat', '')); } }; const syncName = (select, inputId) => { document.getElementById(inputId).value = select.options[select.selectedIndex]?.text ?? ''; }; province.addEventListener('change', async () => { syncName(province, 'province_name'); regency.replaceChildren(new Option('Pilih provinsi terlebih dahulu', '')); district.replaceChildren(new Option('Pilih kabupaten/kota terlebih dahulu', '')); regency.disabled = true; district.disabled = true; if (province.value) await load(endpoint('regencies', province.value), regency, 'Pilih kabupaten/kota', ''); }); regency.addEventListener('change', async () => { syncName(regency, 'regency_name'); district.replaceChildren(new Option('Pilih kabupaten/kota terlebih dahulu', '')); district.disabled = true; if (regency.value) await load(endpoint('districts', regency.value), district, 'Pilih kecamatan', ''); }); district.addEventListener('change', () => syncName(district, 'district_name')); load(endpoint('provinces'), province, 'Pilih provinsi', province.dataset.selectedCode).then(async () => { if (province.value) { await load(endpoint('regencies', province.value), regency, 'Pilih kabupaten/kota', regency.dataset.selectedCode); if (regency.value) await load(endpoint('districts', regency.value), district, 'Pilih kecamatan', district.dataset.selectedCode); } }); })();</script>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css">
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>
    <script>(() => { const mapElement = document.getElementById('business-place-picker-map'); const mapsUrl = document.getElementById('google_maps_url'); const mapsPreviewLink = document.getElementById('maps-preview-link'); const latitude = document.getElementById('latitude'); const longitude = document.getElementById('longitude'); if (!mapElement || !mapsUrl || !latitude || !longitude || typeof L === 'undefined') return; const defaultCoordinates = [-2.5489, 118.0149]; const coordinateFromUrl = url => { if (!url) return null; const match = url.match(/@(-?\d+(?:\.\d+)?),(-?\d+(?:\.\d+)?)/) || url.match(/!3d(-?\d+(?:\.\d+)?)!4d(-?\d+(?:\.\d+)?)/) || url.match(/[?&](?:q|query)=(-?\d+(?:\.\d+)?),(-?\d+(?:\.\d+)?)/); return match ? [Number(match[1]), Number(match[2])] : null; }; const validCoordinates = (coordinates) => coordinates && coordinates.length === 2 && Number.isFinite(coordinates[0]) && Number.isFinite(coordinates[1]) && coordinates[0] >= -90 && coordinates[0] <= 90 && coordinates[1] >= -180 && coordinates[1] <= 180; const storedCoordinates = latitude.value && longitude.value ? [Number(latitude.value), Number(longitude.value)] : null; const urlCoordinates = coordinateFromUrl(mapsUrl.value); const initialCoordinates = validCoordinates(storedCoordinates) ? storedCoordinates : (urlCoordinates || defaultCoordinates); const map = L.map(mapElement).setView(initialCoordinates, validCoordinates(storedCoordinates) || urlCoordinates ? 16 : 5); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; OpenStreetMap contributors' }).addTo(map); let marker = validCoordinates(storedCoordinates) || urlCoordinates ? L.marker(initialCoordinates).addTo(map) : null; const updatePreviewLink = () => { mapsPreviewLink.href = mapsUrl.value || '#'; mapsPreviewLink.classList.toggle('d-none', !mapsUrl.value); }; const setCoordinates = (coordinates, updateLink = true) => { const [lat, lng] = coordinates; latitude.value = lat.toFixed(7); longitude.value = lng.toFixed(7); if (updateLink) mapsUrl.value = `https://www.google.com/maps/@${lat.toFixed(7)},${lng.toFixed(7)},17z`; updatePreviewLink(); if (marker) marker.setLatLng(coordinates); else marker = L.marker(coordinates).addTo(map); }; map.on('click', event => { setCoordinates([event.latlng.lat, event.latlng.lng]); }); mapsUrl.addEventListener('input', () => { const coordinates = coordinateFromUrl(mapsUrl.value); if (!coordinates) { updatePreviewLink(); return; } setCoordinates(coordinates, false); map.setView(coordinates, 16); }); updatePreviewLink(); if (marker) marker.bindPopup('Lokasi tempat bisnis').openPopup(); })();</script>
    <script>(() => { const picker = document.querySelector('[data-category-picker]'); if (!picker) return; const toggle = picker.querySelector('[data-category-toggle]'); const label = picker.querySelector('[data-category-label]'); const selected = picker.querySelector('[data-category-selected]'); const update = () => { const checked = [...picker.querySelectorAll('input[type="checkbox"]:checked')]; label.textContent = checked.length ? `${checked.length} kategori dipilih` : 'Pilih kategori bisnis'; selected.replaceChildren(...checked.map(input => { const chip = document.createElement('span'); chip.className = 'business-category-chip'; chip.textContent = input.dataset.categoryName; return chip; })); }; toggle.addEventListener('click', () => { const open = picker.classList.toggle('is-open'); toggle.setAttribute('aria-expanded', open ? 'true' : 'false'); }); picker.querySelectorAll('input[type="checkbox"]').forEach(input => input.addEventListener('change', update)); document.addEventListener('click', event => { if (!picker.contains(event.target)) { picker.classList.remove('is-open'); toggle.setAttribute('aria-expanded', 'false'); } }); update(); })();</script>
    <script>document.getElementById('cover_image')?.addEventListener('change', event => { const file = event.target.files?.[0]; if (!file) return; const preview = document.getElementById('cover-preview'); const image = document.createElement('img'); image.alt = 'Preview gambar tempat bisnis'; image.src = URL.createObjectURL(file); preview.replaceChildren(image); });</script>
@endsection
